name: Java CI

on:
  push:
    branches: [ main ]  # Укажите вашу основную ветку здесь, например, main или master

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build
        run: javac -cp ./lib/junit-jupiter-api-5.8.1.jar ./src/NumberProcessor.java ./src/NumberProcessorTest.java
      - name: Run
        run: java -jar ./lib/junit-jupiter-api-5.8.1.jar --class-path target --select-class NumberProcessorTest

  build:
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build
        run: javac ./src/NumberProcessor.java
      - name: Run
        run: java -classpath ./src NumberProcessor
